# Basic
title: IMU_Zhouchenyang
subtitle: Chenyang Zhou
description: These violent delights have violent ends.
# 头像里面的标题
avatarTitle: imuzcy
# 头像里面的描述
avatarDesc: Coding·Reading
url: "http://imuzcy.github.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: imuzcy

# Social
social:
    # weibo: 1073227497 
    github: imuzcy
    # twitter: 
    mail: chenyangzhou19940217@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: cf9d171c60e6edab2cff1a2c587aca0f

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-123196754-1
    host: auto  


# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _post/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear #背景Mask

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 存档, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


